---
# defaults file for skupper_cli_install
skupper_cli_install_version: "1.8.3"
skupper_cli_install_os: "linux"
skupper_cli_install_arch: "amd64"
skupper_cli_install_location: "/usr/local/bin"
skupper_cli_install_force: false
