# validating
- name: Validate links to be created
  ansible.builtin.include_tasks: validate.yml

# prepare command
- name: Kubernetes tasks
  ansible.builtin.include_tasks: kube-command.yml
  when: platform == 'kubernetes'
- name: Podman tasks
  ansible.builtin.include_tasks: podman-command.yml
  when: platform == 'podman'

# adding common flags
- name: Adding --name
  ansible.builtin.set_fact:
    skupper_link_command: "{{ skupper_link_command + ['--name', item.name] }}"
  when: item['name'] is defined

- name: Adding --cost
  ansible.builtin.set_fact:
    skupper_link_command: "{{ skupper_link_command + ['--cost', item.cost] }}"
  when: item['cost'] is defined

# Create a temporary file to store the token
- name: Create temporary file for token
  ansible.builtin.tempfile:
    state: file
    suffix: tokentemp
  register: tokentemp

# Saving secret content into the temporary
- name: Saving token file
  ansible.builtin.copy:
    content: "{{ hostvars[item.host]['generatedToken'] }}"
    dest: "{{ tokentemp.path }}"
    mode: '0644'
    remote_src: true

# Add the temp file name to the link create command
- name: Adding temporary file name to link create command
  ansible.builtin.set_fact:
    skupper_link_command: "{{ skupper_link_command + [tokentemp.path] }}"

# executing and validating result
- name: Executing skupper link create
  ansible.builtin.command:
    argv: "{{ skupper_link_command }}"
  register: linkStatus
  changed_when: not linkStatus.failed
  failed_when: >
    linkStatus.failed and
    'Already connected to' not in linkStatus.stderr_lines[0] and
    'already exists' not in linkStatus.stderr_lines[0]
