- name: Preparing init command
  ansible.builtin.set_fact:
    skupper_init_command:
      - skupper
      - init
      - --platform
      - "{{ platform }}"

- name: Adding --kubeconfig
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--kubeconfig', kubeconfig] }}"
  when: kubeconfig is defined and kubeconfig | length() > 0

- name: Adding --context
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--context', context] }}"
  when: context is defined and context | length() > 0

- name: Adding --namespace
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--namespace', namespace] }}"
  when: namespace is defined and namespace | length() > 0

- name: Adding --site-name
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--site-name', init.siteName] }}"
  when: init['siteName'] is defined

- name: Adding --ingress
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--ingress', init.ingress] }}"
  when: init['ingress'] is defined

- name: Adding --router-mode
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-mode', init.routerMode] }}"
  when: init['routerMode'] is defined

- name: Adding --labels
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--labels', item] }}"
  with_items: "{{ init['labels'] }}"
  when: init['labels'] is defined and init['labels'] | length() > 0

- name: Adding --router-logging
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-logging', init.routerLogging] }}"
  when: init['routerLogging'] is defined

- name: Adding --router-debug-mode
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-debug-mode', init.routerDebugMode] }}"
  when: init['routerDebugMode'] is defined

- name: Adding --timeout
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--timeout', init.timeout] }}"
  when: init['timeout'] is defined

- name: Adding --ingress-host
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--ingress-host', init.ingressHost] }}"
  when: init['ingressHost'] is defined

- name: Adding --create-network-policy
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--create-network-policy=' + init.createNetworkPolicy] }}"
  when: init['createNetworkPolicy'] is defined

- name: Adding --enable-service-sync
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--enable-service-sync=' + init.enableServiceSync] }}"
  when: init['enableServiceSync'] is defined

- name: Adding --service-sync-site-ttl
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--service-sync-site-ttl', init.serviceSyncSiteTtl] }}"
  when: init['serviceSyncSiteTtl'] is defined

- name: Adding --enable-console
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--enable-console=' + init.enableConsole] }}"
  when: init['enableConsole'] is defined

- name: Adding --enable-flow-collector
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--enable-flow-collector=' + init.enableFlowCollector] }}"
  when: init['enableFlowCollector'] is defined

- name: Adding --enable-rest-api
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--enable-rest-api=' + init.enableRestApi] }}"
  when: init['enableRestApi'] is defined

- name: Adding --enable-cluster-permissions
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--enable-cluster-permissions=' + init.enableClusterPermissions] }}"
  when: init['enableClusterPermissions'] is defined

- name: Adding --enable-skupper-events
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--enable-skupper-events=' + init.enableSkupperEvents] }}"
  when: init['enableSkupperEvents'] is defined

- name: Adding --console-auth
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--console-auth', init.consoleAuth] }}"
  when: init['consoleAuth'] is defined

- name: Adding --console-user
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--console-user', init.consoleUser] }}"
  when: init['consoleUser'] is defined

- name: Adding --console-password
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--console-password', init.consolePassword] }}"
  when: init['consolePassword'] is defined

- name: Adding --console-ingress
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--console-ingress', init.consoleIngress] }}"
  when: init['consoleIngress'] is defined

- name: Adding --annotations
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--annotations', item] }}"
  with_items: "{{ init['annotations'] }}"
  when: init['annotations'] is defined and init['annotations'] | length() > 0

- name: Adding --ingress-annotations
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--ingress-annotations', item] }}"
  with_items: "{{ init['ingressAnnotations'] }}"
  when: init['ingressAnnotations'] is defined and init['ingressAnnotations'] | length() > 0

- name: Adding --router-service-annotations
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-service-annotations', item] }}"
  with_items: "{{ init['routerServiceAnnotations'] }}"
  when: init['routerServiceAnnotations'] is defined and init['routerServiceAnnotations'] | length() > 0

- name: Adding --controller-service-annotations
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-service-annotations', item] }}"
  with_items: "{{ init['controllerServiceAnnotations'] }}"
  when: init['controllerServiceAnnotations'] is defined and init['controllerServiceAnnotations'] | length() > 0

- name: Adding --routers
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--routers', init.routers] }}"
  when: init['routers'] is defined

- name: Adding --router-cpu
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-cpu', init.routerCpu] }}"
  when: init['routerCpu'] is defined

- name: Adding --router-memory
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-memory', init.routerMemory] }}"
  when: init['routerMemory'] is defined

- name: Adding --router-cpu-limit
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-cpu-limit', init.routerCpuLimit] }}"
  when: init['routerCpuLimit'] is defined

- name: Adding --router-memory-limit
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-memory-limit', init.routerMemoryLimit] }}"
  when: init['routerMemoryLimit'] is defined

- name: Adding --router-node-selector
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-node-selector', init.routerNodeSelector] }}"
  when: init['routerNodeSelector'] is defined

- name: Adding --router-pod-affinity
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-pod-affinity', init.routerPodAffinity] }}"
  when: init['routerPodAffinity'] is defined

- name: Adding --router-pod-antiaffinity
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-pod-antiaffinity', init.routerPodAntiaffinity] }}"
  when: init['routerPodAntiaffinity'] is defined

- name: Adding --router-ingress-host
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-ingress-host', init.routerIngressHost] }}"
  when: init['routerIngressHost'] is defined

- name: Adding --router-load-balancer-ip
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-load-balancer-ip', init.routerLoadBalancerIp] }}"
  when: init['routerLoadBalancerIp'] is defined

- name: Adding --controller-cpu
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-cpu', init.controllerCpu] }}"
  when: init['controllerCpu'] is defined

- name: Adding --controller-memory
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-memory', init.controllerMemory] }}"
  when: init['controllerMemory'] is defined

- name: Adding --controller-cpu-limit
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-cpu-limit', init.controllerCpuLimit] }}"
  when: init['controllerCpuLimit'] is defined

- name: Adding --controller-memory-limit
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-memory-limit', init.controllerMemoryLimit] }}"
  when: init['controllerMemoryLimit'] is defined

- name: Adding --controller-node-selector
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-node-selector', init.controllerNodeSelector] }}"
  when: init['controllerNodeSelector'] is defined

- name: Adding --controller-pod-affinity
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-pod-affinity', init.controllerPodAffinity] }}"
  when: init['controllerPodAffinity'] is defined

- name: Adding --controller-pod-antiaffinity
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-pod-antiaffinity', init.controllerPodAntiaffinity] }}"
  when: init['controllerPodAntiaffinity'] is defined

- name: Adding --controller-ingress-host
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-ingress-host', init.controllerIngressHost] }}"
  when: init['controllerIngressHost'] is defined

- name: Adding --controller-load-balancer-ip
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-load-balancer-ip', init.controllerLoadBalancerIp] }}"
  when: init['controllerLoadBalancerIp'] is defined

- name: Adding --config-sync-cpu
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--config-sync-cpu', init.configSyncCpu] }}"
  when: init['configSyncCpu'] is defined

- name: Adding --config-sync-memory
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--config-sync-memory', init.configSyncMemory] }}"
  when: init['configSyncMemory'] is defined

- name: Adding --config-sync-cpu-limit
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--config-sync-cpu-limit', init.configSyncCpuLimit] }}"
  when: init['configSyncCpuLimit'] is defined

- name: Adding --config-sync-memory-limit
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--config-sync-memory-limit', init.configSyncMemoryLimit] }}"
  when: init['configSyncMemoryLimit'] is defined

- name: Adding --flow-collector-record-ttl
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--flow-collector-record-ttl', init.flowCollectorRecordTtl] }}"
  when: init['flowCollectorRecordTtl'] is defined

- name: Adding --flow-collector-cpu
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--flow-collector-cpu', init.flowCollectorCpu] }}"
  when: init['flowCollectorCpu'] is defined

- name: Adding --flow-collector-memory
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--flow-collector-memory', init.flowCollectorMemory] }}"
  when: init['flowCollectorMemory'] is defined

- name: Adding --flow-collector-cpu-limit
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--flow-collector-cpu-limit', init.flowCollectorCpuLimit] }}"
  when: init['flowCollectorCpuLimit'] is defined

- name: Adding --flow-collector-memory-limit
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--flow-collector-memory-limit', init.flowCollectorMemoryLimit] }}"
  when: init['flowCollectorMemoryLimit'] is defined

- name: Adding --external-prometheus-server
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--external-prometheus-server', init.externalPrometheusServer] }}"
  when: init['externalPrometheusServer'] is defined

- name: Adding --prometheus-cpu
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--prometheus-cpu', init.prometheusCpu] }}"
  when: init['prometheusCpu'] is defined

- name: Adding --prometheus-memory
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--prometheus-memory', init.prometheusMemory] }}"
  when: init['prometheusMemory'] is defined

- name: Adding --prometheus-cpu-limit
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--prometheus-cpu-limit', init.prometheusCpuLimit] }}"
  when: init['prometheusCpuLimit'] is defined

- name: Adding --prometheus-memory-limit
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--prometheus-memory-limit', init.prometheusMemoryLimit] }}"
  when: init['prometheusMemoryLimit'] is defined

- name: Adding --prometheus-auth
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--prometheus-auth', init.prometheusAuth] }}"
  when: init['prometheusAuth'] is defined

- name: Adding --prometheus-user
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--prometheus-user', init.prometheusUser] }}"
  when: init['prometheusUser'] is defined

- name: Adding --prometheus-password
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--prometheus-password', init.prometheusPassword] }}"
  when: init['prometheusPassword'] is defined
