namespace: skupper
name: v2
version: 2.1.3
readme: README.md
authors:
  - Fernando Giorgetti (@fgiorgetti)
description: Collection to manage skupper v2 sites
license_file: 'LICENSE'
tags:
  - skupper
  - networking
  - cloud
  - service
  - interconnect
  - kubernetes
  - openshift
  - podman
  - docker
  - linux
dependencies: {}
repository: https://github.com/skupperproject/skupper-ansible
documentation: https://skupperproject.github.io/skupper-ansible/
homepage: https://skupper.io
issues: http://github.com/skupperproject/skupper-ansible/issues
build_ignore: []
