---
# tasks file for skupper-token
- name: Kubernetes tasks
  ansible.builtin.include_tasks: kube-tasks.yml
  when: platform == 'kubernetes'
- name: Podman tasks
  ansible.builtin.include_tasks: podman-tasks.yml
  when: platform == 'podman'

# Create a temporary file to store the token
- name: Create temporary file for token
  ansible.builtin.tempfile:
    state: file
    suffix: tokentemp
  register: tokentemp

# Add the temp file name to the token create command
- name: Adding temporary file name to token create command
  set_fact:
    skupper_token_command: "{{ skupper_token_command + [tokentemp.path] }}"
  
# executing and validating result
- name: Executing skupper token create
  ansible.builtin.command:
    argv: "{{ skupper_token_command }}"
  register: tokenStatus

# saving generated token into tokens dictionary
- name: Saving token into tokens dictionary
  set_fact:
    generatedToken: "{{ lookup('file', tokentemp.path) }}"
