---
# tasks file for skupper-delete
- name: Kubernetes tasks
  ansible.builtin.include_tasks: kube-tasks.yml
  when: platform == 'kubernetes'
- name: Podman tasks
  ansible.builtin.include_tasks: podman-tasks.yml
  when: platform == 'podman'

# executing and validating result
- name: Executing skupper delete
  ansible.builtin.command:
    argv: "{{ skupper_delete_command }}"
  register: deleteStatus
  failed_when: >
    deleteStatus.failed and
    "Skupper not installed in" not in deleteStatus.stderr_lines[0] and
    "Skupper is not enabled for" not in deleteStatus.stderr_lines[0]
