galaxy_info:
  author: Skupper team
  company: Red Hat
  description: Initializes a Skupper site
  issue_tracker_url: http://github.com/skupper/skupper
  license: Apache-2.0
  min_ansible_version: "2.1"

  galaxy_tags:
    - skupper init

dependencies:
  - role: skupper_common

# collections:
#   - kubernetes.core
