---
# tasks file for skupper-init
- name: Kubernetes tasks
  ansible.builtin.include_tasks: kube-tasks.yml
  when: platform == 'kubernetes'
- name: Podman tasks
  ansible.builtin.include_tasks: podman-tasks.yml
  when: platform == 'podman'

# executing and validating result
- name: Executing skupper init
  ansible.builtin.command:
    argv: "{{ skupper_init_command }}"
  register: initStatus
  failed_when: >
    initStatus.failed and
    "Skupper has already been initialized" not in initStatus.stderr_lines[0]
